# Generated by Django 3.1.5 on 2021-07-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('res_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('res_type', models.CharField(choices=[('1', 'Oxygen-NewCylinder'), ('2', 'Oxygen-Refill'), ('3', 'Beds-Information'), ('4', 'Beds-Formalities'), ('5', 'Medicines')], max_length=1)),
            ],
        ),
    ]
