# Generated by Django 3.1.5 on 2021-07-10 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AidLink', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('donation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount_wanting', models.IntegerField(max_length=10)),
                ('amount_raised', models.IntegerField(max_length=10)),
                ('other_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Resources_Others',
            fields=[
                ('res_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('res_type', models.CharField(choices=[('0', 'Food'), ('1', 'Groceries'), ('2', 'Amenities')], max_length=1)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('contact_Call', models.CharField(max_length=10)),
                ('contact_WA', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteers',
            fields=[
                ('volunteer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('contact_Call', models.CharField(max_length=10)),
                ('contact_WA', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=25)),
                ('other_types', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='medical',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='medical',
            name='contact_Call',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='medical',
            name='contact_WA',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='medical',
            name='email',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='medical',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='medical',
            name='res_type',
            field=models.CharField(choices=[('0', 'Oxygen-NewCylinder'), ('1', 'Oxygen-Refill'), ('2', 'Beds-Information'), ('3', 'Beds-Formalities'), ('4', 'Medicines')], max_length=1),
        ),
        migrations.CreateModel(
            name='ReciverDetails',
            fields=[
                ('reciever_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('contact_Call', models.CharField(max_length=10)),
                ('contact_WA', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=25)),
                ('donation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AidLink.donations')),
            ],
        ),
        migrations.CreateModel(
            name='DonorDetails',
            fields=[
                ('donor_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('contact_Call', models.CharField(max_length=10)),
                ('contact_WA', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=25)),
                ('donation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AidLink.donations')),
            ],
        ),
    ]
