# Generated by Django 3.1.5 on 2021-07-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AidLink', '0002_auto_20210710_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='amount_raised',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='donations',
            name='amount_wanting',
            field=models.IntegerField(),
        ),
    ]
