# Generated by Django 3.1.5 on 2021-07-10 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AidLink', '0003_auto_20210710_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_type', models.CharField(choices=[('0', 'Oxygen-NewCylinder'), ('1', 'Oxygen-Refill'), ('2', 'Beds-Information'), ('3', 'Beds-Formalities'), ('4', 'Medicines'), ('5', 'FoodDelivery'), ('6', 'Groceries'), ('7', 'Amenities'), ('8', 'Floating'), ('9', 'Others')], max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Medical',
        ),
        migrations.DeleteModel(
            name='Resources_Others',
        ),
        migrations.RemoveField(
            model_name='volunteers',
            name='other_types',
        ),
        migrations.AddField(
            model_name='resource',
            name='volunteer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AidLink.volunteers'),
        ),
    ]
