# Generated by Django 3.1.5 on 2021-07-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AidLink', '0004_auto_20210710_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteers',
            name='pincode',
            field=models.CharField(default='700035', max_length=10),
        ),
    ]
