# Generated by Django 3.1.5 on 2021-07-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AidLink', '0005_volunteers_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='id',
        ),
        migrations.AddField(
            model_name='resource',
            name='res_id',
            field=models.BigAutoField(default='0', primary_key=True, serialize=False),
        ),
    ]
