# Generated by Django 3.1.5 on 2021-07-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AidLink', '0006_auto_20210710_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='volunteer_id',
            field=models.IntegerField(),
        ),
    ]
