# Generated by Django 3.1.5 on 2021-07-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AidLink', '0009_auto_20210711_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='cause_type',
            field=models.CharField(choices=[('0', 'Covid-19'), ('1', 'Vaccination'), ('2', 'Medicines'), ('3', 'Transplant'), ('4', 'Others')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='donations',
            name='donation_type',
            field=models.CharField(choices=[('0', 'Fundraiser'), ('1', 'Donation')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='donordetails',
            name='donation_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reciverdetails',
            name='donation_id',
            field=models.IntegerField(),
        ),
    ]
